'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,Check,ChefHat,Cookie,Leaf,MapPin,Moon,Sun,Sunrise,Truck} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {packages,recipes,articles,money,type Recipe} from '@/lib/data';
import {shopProducts} from '@/lib/commerce';
import {FoodImage} from './shell';
import {PackageCard,HowSteps,ArticleCard,RecipeDialog} from './pages';
const dayMeals=[{value:'sabah',title:'Sabah',Icon:Sunrise,id:'granola',line:'Güne güzel bir başlangıç.'},{value:'ogle',title:'Öğle',Icon:Sun,id:'tavuk-bowl',line:'Günün tam ortasında, tam sana göre.'},{value:'aksam',title:'Akşam',Icon:Moon,id:'somon',line:'Uzun bir günün lezzetli finali.'},{value:'mola',title:'İyi molalar',Icon:Cookie,id:'meyveli-yogurt',line:'Küçük bir mola. Kocaman bir iyi his.'}];
export function BrandHome(){const [detail,setDetail]=useState<Recipe|null>(null);return <>
  <div className="brand-announcement"><MapPin size={14}/><span>Şimdilik sadece İstanbul'dayız.</span><Link href="/nasil-calisir#sss">Teslimatı keşfet<ArrowUpRight size={14}/></Link></div>
  <section className="brand-hero wrap"><div className="brand-hero-copy"><span className="eyebrow">GÜZEL BİR GÜN, İYİ BİR ÖĞÜNLE BAŞLAR.</span><h1>İyi beslen.<br/><span>İyi hisset.</span></h1><p>Hayat dolu günlerine, özenle hazırlanmış öğünler. Sen kendine zaman ayır; mutfağı bize bırak.</p><div className="brand-hero-actions"><Link href="/siparis-olustur" className="button black">Paketini oluştur<ArrowUpRight size={20}/></Link><Link href="/menu" className="text-link">Menüye göz at<ArrowRight size={17}/></Link></div><div className="hero-service-note"><span><ChefHat size={19}/>Şef dokunuşu</span><span><Leaf size={19}/>Diyetisyen dengesi</span></div></div><div className="brand-hero-visual"><FoodImage src="/images/zepe-hero-food.png" alt="Sebzeli tavuk bowl, günlük öğün kutusu ve yeşil içecekten oluşan temsili Zepe sofrası" className="brand-hero-photo" priority/><div className="hero-image-caption"><span>DAHA ÇOK YAŞAM.<br/>DAHA AZ MUTFAK TELAŞI.</span><span className="hero-image-mark">zepe.</span></div></div></section>
  <div className="brand-benefits"><div className="wrap"><span><ChefHat size={21}/>Özenle hazırlanan öğünler</span><span><Truck size={21}/>İstanbul'a günlük teslimat</span><span><Leaf size={21}/>Sana göre porsiyonlar</span><span><Check size={21}/>Programa göre dahil molalar</span></div></div>
  <section className="wrap section brand-packages"><div className="section-head"><div><span className="eyebrow">SENİN HAYATIN. SENİN RİTMİN.</span><h2>Bir paket dolusu<br/>kendine iyi bakma hali.</h2></div><div><p>Hedefine, gününe, iştahına göre.<br/>Seninle uyumlu bir Zepe mutlaka var.</p><Link href="/paketler" className="text-link">Tüm paketleri keşfet<ArrowUpRight size={18}/></Link></div></div><div className="card-grid">{packages.slice(0,3).map(p=><PackageCard key={p.id} p={p}/>)}</div><p className="fine section-footnote">Günlük başlangıç fiyatlarıdır. İçerik ve kesin fiyat, kişisel planınla netleşir. Fotoğraflar temsili sunumdur.</p></section>
  <section className="day-story"><div className="wrap"><div className="section-head"><div><span className="eyebrow">SABAHTAN AKŞAMA, YANINDA.</span><h2>Günün iyi hali.</h2></div><Link href="/menu" className="text-link">Haftalık örnek menü<ArrowUpRight size={18}/></Link></div><Tabs defaultValue="ogle" className="day-story-tabs"><TabsList>{dayMeals.map(m=><TabsTrigger key={m.value} value={m.value}><m.Icon size={19}/>{m.title}</TabsTrigger>)}</TabsList>{dayMeals.map(m=>{const r=recipes.find(r=>r.id===m.id)!;return <TabsContent value={m.value} key={m.value}><div className="day-story-content"><FoodImage src={r.image} alt={`${r.name}, örnek sunum`} className="day-story-photo"/><div className="day-story-copy"><span className="eyebrow">{m.title} · ÖRNEK MENÜ</span><h3>{m.line}</h3><h4>{r.name}</h4><p>{r.description}</p><div className="day-story-macros"><span><strong>{r.kcal}</strong> kcal</span><span><strong>{r.protein} g</strong> protein</span></div>{m.value==='mola'&&<p className="included-story"><Check size={16}/>Paketindeki ara öğünler otomatik dahil.</p>}<button className="text-link" onClick={()=>setDetail(r)}>İçeriği ve alerjenleri incele<ArrowRight size={17}/></button><p className="fine">Besin değerleri yaklaşık / örnek porsiyon.</p></div></div></TabsContent>})}</Tabs></div></section>
  <section className="brand-how section"><div className="wrap"><div className="section-head"><div><span className="eyebrow">BİRKAÇ KÜÇÜK SEÇİM.</span><h2>İyi beslenmek,<br/>bu kadar kolay.</h2></div><Link href="/nasil-calisir" className="button secondary">Zepe nasıl çalışır?<ArrowUpRight size={18}/></Link></div><HowSteps/></div></section>
  <section className="wrap section"><div className="section-head"><div><span className="eyebrow">ZEPE MAĞAZA</span><h2>Bugün canın ne istiyor?</h2></div><Link href="/magaza" className="text-link">Mağazaya git<ArrowUpRight size={18}/></Link></div><div className="home-shop-grid">{shopProducts.slice(0,3).map(p=><Link href="/magaza" className="home-shop-card" key={p.id}><FoodImage src={p.image} alt={`${p.name}, temsili sunum`} className=""/><div><span className="fine">{p.category} · {p.unit}</span><h3>{p.name}</h3><div className="row"><strong>{money(p.price)}</strong><span className="round-link"><ArrowUpRight size={18}/></span></div></div></Link>)}</div><p className="fine section-footnote">Örnek mağaza ürünleri ve fiyatları. Online ödeme alınmaz.</p></section>
  <section className="wrap brand-journal"><div className="section-head"><div><span className="eyebrow">İYİ YAŞAMA DAİR</span><h2>Biraz bilgi, bolca ilham.</h2></div><Link href="/kesfet" className="text-link">Keşfet<ArrowUpRight size={18}/></Link></div><div className="journal-grid">{articles.slice(0,3).map(a=><ArticleCard a={a} key={a.id}/>)}</div></section>
  <section className="brand-final-cta"><div className="wrap"><span className="eyebrow">KENDİNE AYIRDIĞIN ZAMAN, EN GÜZELİ.</span><h2>Hayatın tadı<br/>sana kalsın.</h2><Link href="/siparis-olustur" className="button black">Paketini oluşturmaya başla<ArrowUpRight size={20}/></Link></div></section>
  <RecipeDialog recipe={detail} onClose={()=>setDetail(null)}/>
</>}
