'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,ArrowLeft,ArrowUpRight,Check,CalendarDays,Sun,ChevronDown,MapPin,Leaf,ReceiptText} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
import {useSite,FoodImage} from './shell';
import {PackageOptions,PackageConfigurator,PackageControlsSheet} from './package-configuration';
import {AllergenFields,BillingFields,DeliveryFields} from './checkout-fields';
import {packages,money} from '@/lib/data';
import {pricing,quote,mealSummary,selectionsValid,type MealKey} from '@/lib/pricing';
import {nextDate,type CartItem,type Profile} from '@/lib/model';
import {allergyError,billingError,deliveryError,type Billing} from '@/lib/commerce';
import {validFutureDate} from '@/lib/checkout';
const mealOrder:MealKey[]=['breakfast','lunch','dinner'];
const steps=['Paketin','Tercihlerin','Teslimat','Fatura','Özet'];
const titles=['İyi yemek. Senin düzenin.','Önce seni tanıyalım.','Güzel şeyler kapına gelsin.','Faturan nasıl olsun?','Her şey hazır. Bir göz atalım.'];
const descriptions=['Paketini seç. Öğünleri ve günleri hayatına göre ayarla.','Alerjilerini, hassasiyetlerini ve sevmediğin malzemeleri belirt.','İstanbul adresini ve başlangıç tercihini ekle.','Bireysel ya da kurumsal fatura bilgilerini tamamla.','Paketin, beslenme tercihlerin ve teslimat bilgilerin bir arada.'];

export function OrderBuilder({initialPackage='dengeli-beslenme'}:{initialPackage?:string}){
  const {state,user,loaded,save,mutate,busy,error:loadError,reload}=useSite();
  const initial=pricing[initialPackage]?initialPackage:'dengeli-beslenme';
  const [packageId,setPackageId]=useState(initial),[days,setDays]=useState(5),[people,setPeople]=useState('1');
  const [meals,setMeals]=useState<MealKey[]>(pricing[initial].defaults);
  const [step,setStep]=useState(0),[profile,setProfile]=useState<Profile>(state.profile),[billing,setBilling]=useState<Billing>(state.billing);
  const [date,setDate]=useState(nextDate(2)),[notes,setNotes]=useState(''),[consent,setConsent]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
  const [mobileControls,setMobileControls]=useState(false),[mobileSection,setMobileSection]=useState<'meals'|'days'>('meals');
  const [draftId]=useState(()=>typeof crypto!=='undefined'?crypto.randomUUID():'');
  const hydrated=useRef(false);
  useEffect(()=>{if(loaded&&!hydrated.current){hydrated.current=true;const name=state.profile.name||user?.name||'';setProfile({...state.profile,name});setBilling({...state.billing,name:state.billing.name||name,email:state.billing.email||user?.email||''});}},[loaded,state.profile,state.billing,user]);
  const cfg=pricing[packageId],pkg=packages.find(p=>p.id===packageId)!;
  const selection={packageId,days,people:Number(people),selectedMeals:meals,snacks:cfg.snacks};
  const price=quote(selection),valid=selectionsValid(selection);
  const configuration={packageId,days,people,meals,onDaysChange:setDays,onPeopleChange:setPeople,onMealChange:toggleMeal,price,valid,busy};
  function selectPackage(id:string){const c=pricing[id];setPackageId(id);setMeals(current=>current.length>=c.min&&current.length<=c.max&&current.every(m=>c.allowed.includes(m))?current:c.defaults);setDays(d=>c.days.includes(d)?d:c.days[0]);setError('');}
  function toggleMeal(m:MealKey){setError('');if(!cfg.allowed.includes(m))return;if(cfg.max===1){setMeals([m]);return;}setMeals(current=>current.includes(m)?current.filter(x=>x!==m):current.length<cfg.max?mealOrder.filter(x=>current.includes(x)||x===m):current);}
  function go(s:number){setStep(s);setMobileControls(false);setError('');window.scrollTo({top:0,behavior:'smooth'});}
  function openControls(section:'meals'|'days'){setMobileSection(section);setMobileControls(true);}
  function stageError(s:number){if(s===0&&!valid)return `Bu paket için ${cfg.min===cfg.max?cfg.min:`en az ${cfg.min}`} ana öğün seç.`;if(s===1)return allergyError(profile);if(s===2)return deliveryError(profile)||(!validFutureDate(date,nextDate(0))?'Bugünden sonraki geçerli bir başlangıç tarihi seç.':'');if(s===3)return billingError(billing,profile);return '';}
  async function advance(e:React.FormEvent){e.preventDefault();setError('');const issue=stageError(step);if(issue){setError(issue);return;}if(step<4){if(step===2&&!billing.name)setBilling({...billing,name:profile.name});go(step+1);return;}for(let i=0;i<4;i++){const issue=stageError(i);if(issue){setStep(i);setError(issue);return;}}if(!consent){setError('Sipariş taslağı bilgisini onayla.');return;}if(!loaded||!user){setError('Taslağını kaydetmek için hesabına giriş yapmalısın.');return;}const item:CartItem={id:draftId,packageId,days:days as CartItem['days'],people:Number(people),selectedMeals:meals,snacks:cfg.snacks,mealOption:mealSummary(selection),startDate:date,notes};if(!await save({profile,billing,cart:[...state.cart.filter(x=>x.id!==draftId),item]}))return;if(await mutate('POST',{itemId:draftId})){setDone(true);toast.success('Sipariş taslağın kaydedildi.');window.scrollTo({top:0,behavior:'smooth'});}}
  const nextLabel=step===4?'Taslağımı kaydet':step===0?'Tercihlere geç':'Devam et';
  const disabled=busy||(step===0&&!valid)||(step===4&&!consent);
  if(done){const latest=state.orders[0];return <div className="wrap page"><div className="order-success"><div className="order-success-icon"><Check size={36}/></div><span className="eyebrow">Kendine iyi bir başlangıç</span><h1>Seçimlerin hazır.</h1><p>{pkg.name} · {days} gün · {mealSummary(selection)}</p><div className="white-panel order-receipt"><div className="row"><span>Sipariş taslağı</span><strong>{latest?.id}</strong></div><div className="row"><span>Tahmini toplam</span><strong className="price">{money(price.total)}</strong></div><p className="fine">Alerjen, teslimat ve fatura tercihlerin kaydedildi. Ödeme alınmadı; siparişin Zepe ile onaylandıktan sonra tamamlanır.</p></div><a className="button" target="_blank" rel="noreferrer" href={`https://wa.me/905332202749?text=${encodeURIComponent(`Merhaba, ${latest?.id||''} numaralı Zepe taslağımı tamamlamak istiyorum. ${pkg.name}, ${days} gün, ${people} kişi. ${mealSummary(selection)}. Başlangıç ${date}, teslimat ilçesi ${profile.district}. Tahmini toplam ${money(price.total)}. Sipariş detaylarını birlikte onaylayabilir miyiz?`)}`}>Zepe ile tamamla<ArrowUpRight size={17}/></a><Link className="text-link success-account-link" href="/hesabim">Hesabıma git<ArrowRight size={16}/></Link></div></div>;}
  return <div className="order-flow">
    <div className="order-progress"><div className="wrap"><ol aria-label="Sipariş adımları">{steps.map((label,i)=><li key={label} className={i===step?'current':i<step?'complete':''}><button type="button" disabled={i>step} onClick={()=>go(i)} aria-current={i===step?'step':undefined}><span className="step-circle">{i<step?<Check size={15}/>:i+1}</span><span>{label}</span></button></li>)}</ol></div></div>
    <div className="wrap"><header className="order-heading"><span className="eyebrow">{step+1} / {steps.length} · Sana göre Zepe</span><h1>{titles[step]}</h1><p>{descriptions[step]}</p></header>
      {step===0&&<div className="mobile-plan-selectors"><button type="button" onClick={()=>openControls('meals')}><Sun size={21}/><span><small>Öğünleri seç</small><strong>{cfg.max===0?`${cfg.drinkCount} içecek`:meals.length?meals.map(m=>({breakfast:'Sabah',lunch:'Öğle',dinner:'Akşam'}[m])).join(' · '):'Öğün seç'}</strong></span><ChevronDown size={17}/></button><button type="button" onClick={()=>openControls('days')}><CalendarDays size={21}/><span><small>Günleri seç</small><strong>{days} gün · {people} kişi</strong></span><ChevronDown size={17}/></button></div>}
      <form id="order-builder" onSubmit={advance} noValidate><div className="order-layout"><div className="order-options">
        {step===0&&<PackageOptions packageId={packageId} onPackageChange={selectPackage} days={days}/>}
        {step===1&&<section className="order-section"><div className="order-section-title"><Leaf size={25}/><div><h2>Alerjenler & beslenme tercihleri</h2><p>Tercihlerini taslağına ekleyelim; uygunluğu Zepe ekibiyle netleştir.</p></div></div><AllergenFields p={profile} setP={setProfile}/></section>}
        {step===2&&<><section className="order-section"><div className="order-section-title"><MapPin size={25}/><div><h2>İletişim & teslimat adresi</h2><p>Evine, ofisine, İstanbul'daki adresine.</p></div></div><DeliveryFields p={profile} setP={setProfile}/></section><section className="order-section"><div className="order-section-title"><CalendarDays size={25}/><div><h2>Ne zaman başlayalım?</h2><p>{days} günlük paketinin başlangıç tercihi.</p></div></div><div className="delivery-dates">{Array.from({length:6},(_,i)=>{const ds=nextDate(i+1),d=new Date(ds+'T12:00:00');return <button type="button" key={ds} onClick={()=>setDate(ds)} aria-pressed={date===ds} className={`day-button ${date===ds?'active':''}`}><span>{d.toLocaleDateString('tr-TR',{weekday:'short'})}</span><strong>{d.getDate()}</strong><span>{d.toLocaleDateString('tr-TR',{month:'short'})}</span></button>;})}</div><label className="form-field checkout-spaced">Başka bir tarih seç<input className="field-input" type="date" min={nextDate()} value={date} onChange={e=>setDate(e.target.value)} required/></label><label className="form-field checkout-spaced">Teslimat notun<textarea className="field-input" rows={3} maxLength={500} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Zil, kat veya teslimatla ilgili notun…"/></label><p className="fine checkout-spaced">Tercih ettiğin gün ve teslimat saati Zepe ekibiyle netleşir.</p></section></>}
        {step===3&&<section className="order-section"><div className="order-section-title"><ReceiptText size={25}/><div><h2>Fatura bilgileri</h2><p>Faturanda yer alacak bilgileri ekle.</p></div></div><BillingFields value={billing} onChange={setBilling} profile={profile}/></section>}
        {step===4&&<><section className="order-section"><div className="row"><h2>Senin paketin</h2><button type="button" className="text-link" onClick={()=>go(0)}>Düzenle</button></div><div className="order-review-product"><FoodImage src={pkg.image} alt="" className=""/><div><h3>{pkg.name}</h3><p>{days} gün · {people} kişi</p><p>{mealSummary(selection)}</p></div></div></section><section className="order-section review-section"><div className="row"><h2>Beslenme tercihlerin</h2><button type="button" className="text-link" onClick={()=>go(1)}>Düzenle</button></div><p>{profile.allergens.length?profile.allergens.join(', '):'Bilinen alerji bildirilmedi.'}</p>{profile.allergyNotes&&<p>{profile.allergyNotes}</p>}{profile.exclusions&&<p>Sevmediğin malzemeler: {profile.exclusions}</p>}</section><section className="order-section review-section"><div className="row"><h2>Adres & teslimat</h2><button type="button" className="text-link" onClick={()=>go(2)}>Düzenle</button></div><strong>{profile.name}</strong><p>{profile.phone}<br/>{profile.address}<br/>{profile.district} / İstanbul</p><p>Başlangıç tercihi: {new Date(date+'T12:00:00').toLocaleDateString('tr-TR')}</p>{notes&&<p>Notun: {notes}</p>}</section><section className="order-section review-section"><div className="row"><h2>Faturan</h2><button type="button" className="text-link" onClick={()=>go(3)}>Düzenle</button></div><strong>{billing.type==='individual'?billing.name:billing.companyName}</strong><p>{billing.email}</p><p>{billing.sameAsDelivery?profile.address:billing.address}<br/>{billing.sameAsDelivery?profile.district:billing.district} / {billing.sameAsDelivery?'İstanbul':billing.city}</p>{billing.type==='company'&&<p>{billing.taxOffice} · {billing.taxNumber}</p>}</section><section className="order-section"><label className="checkbox-label checkout-consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>Alerjen ve fatura bilgilerim dahil, paylaştığım bilgilerin hesabımdaki sipariş taslağına kaydedilmesini onaylıyorum. Bu adımda ödeme alınmaz. Kesin fiyat ve teslimat Zepe ile onaylanır. <Link href="/gizlilik">Gizlilik bilgisini</Link> okudum.</span></label>{!user&&loaded&&<p className="checkout-spaced">Taslağını kaydetmek için <Link className="text-link" href="/hesabim">hesabına giriş yap.</Link></p>}{loadError&&<div><p className="error-text">{loadError}</p><button type="button" className="text-link" onClick={reload}>Tekrar yükle</button></div>}</section></>}
        {error&&<p className="error-text" role="alert">{error}</p>}{step>0&&<button className="text-link order-back" type="button" onClick={()=>go(step-1)}><ArrowLeft size={16}/>Önceki adım</button>}
      </div>{step===0?<PackageConfigurator {...configuration}/>:<aside className="order-summary checkout-summary"><div className="order-summary-top"><span className="eyebrow">Senin paketin</span><h2>{pkg.name}</h2><p>{days} gün · {people} kişi</p></div><div className="order-summary-body"><p className="checkout-meals">{mealSummary(selection)}</p><div className="checkout-includes"><Check size={15}/><span>{cfg.snacks>0?`${cfg.snacks} ara öğün`: `${cfg.drinkCount} detoks içeceği`} her gün dahil</span></div>{step>1&&<p className="fine checkout-spaced">{profile.allergens.length?`${profile.allergens.length} alerjen bildirildi`:'Bilinen alerji bildirilmedi'}</p>}<hr className="divider"/><div className="row"><span>Günlük / kişi</span><strong>{money(price.daily)}</strong></div><div className="row order-total checkout-spaced"><strong>Tahmini toplam</strong><strong>{money(price.total)}</strong></div><p className="fine checkout-spaced">Örnek fiyatlandırma. Kesin fiyat ve teslimat bedeli Zepe ile onaylanır.</p><button className="button full black desktop-continue checkout-spaced" type="submit" disabled={disabled}>{nextLabel}<ArrowRight size={17}/></button><p className="fine order-payment-note"><Check size={13}/>Bu adımda ödeme alınmaz.</p></div></aside>}</div></form>
    </div>
    <div className="order-mobile-bar"><div><span>Tahmini toplam · {days} gün</span><strong aria-live="polite">{money(price.total)}</strong>{step===0&&<button type="button" className="mobile-configure-button" onClick={()=>openControls('meals')}>Öğün ve günleri düzenle<ChevronDown size={14}/></button>}</div><button type="submit" form="order-builder" className="button black" disabled={disabled}>{step===4?'Taslağı kaydet':step===0?'Tercihlere geç':'Devam et'}<ArrowRight size={16}/></button></div>
    {step===0&&<PackageControlsSheet {...configuration} initialSection={mobileSection} open={mobileControls} onOpenChange={setMobileControls}/>}
  </div>;
}
