'use client';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,MapPin,Menu,ShoppingBag,UserRound,ChevronRight,Leaf} from 'lucide-react';
import {Toaster,toast} from 'sonner';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectContent,SelectValue,SelectItem} from '@/components/ui/select';
import {initialState,type State} from '@/lib/model';
import {DistrictSelect} from './checkout-fields';
type Context={state:State;loaded:boolean;busy:boolean;error:string;user:{name:string;email:string}|null;save:(patch:Partial<State>)=>Promise<boolean>;mutate:(method:string,extra?:object)=>Promise<boolean>;reload:()=>void};
type StateResponse={state:State;version:number;user:Context['user'];error?:string};
const SiteContext=createContext<Context>(null!);
export const useSite=()=>useContext(SiteContext);
export function Choice({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="field-select" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export function Shell({children}:{children:ReactNode}){const path=usePathname();const [state,setState]=useState<State>(initialState);const [loaded,setLoaded]=useState(false);const [user,setUser]=useState<Context['user']>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const version=useRef(0);const locked=useRef(false);const [mobile,setMobile]=useState(false);const [location,setLocation]=useState(false);const [district,setDistrict]=useState('');const [checked,setChecked]=useState(false);
async function reload(){setLoaded(false);setError('');try{const r=await fetch('/api/state',{cache:'no-store'});const d=await r.json() as StateResponse;if(r.status===401){setUser(null);return}if(!r.ok||!d.state||!Number.isInteger(d.version))throw new Error(d.error||'Hesap bilgilerini yeniden yükle.');setState(d.state);version.current=d.version;setUser(d.user);}catch(e){setError(e instanceof Error?e.message:'Hesabın yüklenemedi.')}finally{setLoaded(true)}}
useEffect(()=>{reload()},[]);useEffect(()=>{setMobile(false)},[path]);
async function mutate(method:string,extra:object={}){if(locked.current)return false;if(!loaded){toast('Hesabın yükleniyor. Lütfen tekrar dene.');return false}if(!user){toast.error('Kaydetmek için hesabına giriş yap.');return false}locked.current=true;setBusy(true);try{const r=await fetch('/api/state',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({version:version.current,...extra})});const d=await r.json() as StateResponse;if(!r.ok||!d.state||!Number.isInteger(d.version))throw new Error(d.error||'Hesap bilgilerini yeniden yükle.');version.current=d.version;setState(d.state);setError('');return true}catch(e){toast.error(e instanceof Error?e.message:'Kaydedilemedi.');return false}finally{locked.current=false;setBusy(false)}}
const cartCount=state.cart.length+state.shopCart.reduce((sum,item)=>sum+item.quantity,0);
const save=(patch:Partial<State>)=>mutate('PUT',{patch});const links=[['Paketler','/paketler'],['Menüler','/menu'],['Mağaza','/magaza'],['Nasıl çalışır?','/nasil-calisir'],['Keşfet','/kesfet']];
return <SiteContext.Provider value={{state,loaded,user,error,busy,save,mutate,reload}}><a className="skip-link" href="#main">İçeriğe geç</a><header className="site-nav"><div className="wrap nav-inner"><Link href="/" className="logo" aria-label="Zepe ana sayfa">zepe<i>.</i></Link><nav className="nav-links" aria-label="Ana menü">{links.map(([label,href])=><Link key={href} href={href} className={path.startsWith(href)?'active':''}>{label}</Link>)}</nav><div className="nav-tools"><button className="text-link desktop-only" onClick={()=>setLocation(true)}><MapPin size={15}/>İstanbul</button><Link className="icon-btn" href="/hesabim" aria-label="Hesabım"><UserRound size={20}/></Link><Link className="icon-btn" href="/sepet" aria-label={`Sepetim, ${cartCount} ürün`}><ShoppingBag size={20}/>{cartCount>0&&<span className="count">{cartCount}</span>}</Link><Link href="/siparis-olustur" className="button small black desktop-only">Paketini oluştur</Link><button className="icon-btn mobile-toggle" aria-label="Menüyü aç" onClick={()=>setMobile(true)}><Menu size={22}/></button></div></div></header><main id="main">{children}</main><footer className="site-footer"><div className="wrap"><div className="footer-main"><div className="footer-brand"><Link href="/" className="logo">zepe<i>.</i></Link><p>İyi beslenmek, hayatının doğal bir parçası olsun.</p></div><div className="footer-col"><h4>Sana özel</h4><Link href="/paketler">Yemek paketleri</Link><Link href="/siparis-olustur">Aboneliğini oluştur</Link><Link href="/menu">Menüyü keşfet</Link><Link href="/magaza">Mağaza</Link><Link href="/paketler#karsilastir">Paketleri karşılaştır</Link><Link href="/planim">Haftalık planım</Link><Link href="/planini-olustur">Planını oluştur</Link></div><div className="footer-col"><h4>Zepe'yi tanı</h4><Link href="/nasil-calisir">Nasıl çalışır?</Link><Link href="/kesfet">İyi yaşam rehberi</Link><Link href="/iletisim">Kurumsal çözümler</Link><Link href="/nasil-calisir#sss">Sıkça sorulanlar</Link></div><div className="footer-col"><h4>Bir merhaba de</h4><a href="mailto:info@zepeapp.com">info@zepeapp.com</a><a href="tel:+905332202749">+90 533 220 27 49</a><Link href="/iletisim">Bize ulaş <ArrowUpRight size={14} style={{display:'inline'}}/></Link></div></div><div className="footer-wordmark" aria-hidden="true">zepe<span>.</span></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Zepe. Her gün kendine iyi bak.</span><div style={{display:'flex',gap:22}}><Link href="/gizlilik">Gizlilik & kullanım</Link><Link href="/kaynaklar">Kaynaklar</Link></div></div></div></footer>
<Sheet open={mobile} onOpenChange={setMobile}><SheetContent style={{padding:30}}><SheetTitle className="logo">zepe<span style={{color:'var(--brand)'}}>.</span></SheetTitle><SheetDescription>Hayatına uyum sağlayan beslenme.</SheetDescription><nav className="mobile-menu">{links.map(([label,href])=><Link key={href} href={href} onClick={()=>setMobile(false)}>{label}</Link>)}<Link href="/planim">Haftalık planım</Link><Link href="/iletisim">İletişim</Link><Link href="/siparis-olustur" className="button">Paketini oluştur</Link><button className="text-link" onClick={()=>{setMobile(false);setLocation(true)}}><MapPin size={18}/>Teslimat bölgesi</button></nav></SheetContent></Sheet>
<Dialog open={location} onOpenChange={setLocation}><DialogContent className="modal-body" style={{borderRadius:24,padding:30}}><MapPin size={30} color="var(--brand)"/><DialogTitle className="modal-title">Sana da gelelim.</DialogTitle><DialogDescription>İstanbul'daki adresin için güncel teslimat uygunluğunu Zepe ekibiyle kontrol et.</DialogDescription><label className="form-field">İlçe<DistrictSelect value={district} onChange={value=>{setDistrict(value);setChecked(false)}}/></label><button className="button full" onClick={()=>setChecked(true)} disabled={!district.trim()}>Teslimat bilgisini gör <ChevronRight size={17}/></button>{checked&&<div className="panel"><p style={{fontSize:14}}>{district} için teslimat gününü ve saatini adres bazında Zepe ekibi netleştirir.</p><a className="text-link" style={{marginTop:14}} href={`https://wa.me/905332202749?text=${encodeURIComponent(`Merhaba, İstanbul ${district} için teslimat uygunluğunu öğrenmek istiyorum.`)}`} target="_blank" rel="noreferrer">WhatsApp'ta sor <ArrowUpRight size={16}/></a></div>}</DialogContent></Dialog><Toaster position="bottom-center" richColors closeButton/></SiteContext.Provider>}
export function LoadGate({children}:{children:ReactNode}){const s=useSite();const path=usePathname();if(!s.loaded)return <div className="loading-state" role="status">Hesabın yükleniyor…</div>;if(s.error)return <div className="empty-state"><h2>Bir kez daha deneyelim.</h2><p>{s.error}</p><button className="button" onClick={s.reload}>Yeniden dene</button></div>;if(!s.user)return <div className="empty-state"><UserRound size={40}/><h2>Sana ait bir alan.</h2><p>Planını, favorilerini ve sipariş taslaklarını hesabında sakla.</p><a href={`/signin-with-chatgpt?return_to=${encodeURIComponent(path)}`} target="_top" className="button">ChatGPT ile giriş yap</a></div>;return <>{children}</>}
export function FoodImage({src,alt,className='food-img',priority=false}:{src:string;alt:string;className?:string;priority?:boolean}){const[failed,setFailed]=useState(false);return failed?<div className={className} style={{background:'var(--soft)',display:'grid',placeItems:'center',color:'#aaa'}}><Leaf size={35}/><span className="fine">Fotoğraf yüklenemedi</span></div>:<img src={src} alt={alt} className={className} loading={priority?'eager':'lazy'} decoding="async" onError={()=>setFailed(true)}/>}
