import {z} from 'zod';
import {recipes} from './data';

export const istanbulDistricts=['Adalar','Arnavutköy','Ataşehir','Avcılar','Bağcılar','Bahçelievler','Bakırköy','Başakşehir','Bayrampaşa','Beşiktaş','Beykoz','Beylikdüzü','Beyoğlu','Büyükçekmece','Çatalca','Çekmeköy','Esenler','Esenyurt','Eyüpsultan','Fatih','Gaziosmanpaşa','Güngören','Kadıköy','Kağıthane','Kartal','Küçükçekmece','Maltepe','Pendik','Sancaktepe','Sarıyer','Silivri','Sultanbeyli','Sultangazi','Şile','Şişli','Tuzla','Ümraniye','Üsküdar','Zeytinburnu'] as const;
export const allergens=['Gluten','Süt','Yumurta','Kuruyemiş','Yer fıstığı','Soya','Balık','Kabuklular','Yumuşakçalar','Susam','Hardal','Kereviz','Acı bakla','Sülfitler'] as const;
export type Allergen=typeof allergens[number];
export const allergenDetails:Record<Allergen,string>={Gluten:'Buğday, arpa, çavdar, yulaf',Süt:'Süt ve süt ürünleri',Yumurta:'Yumurta ve içeren ürünler',Kuruyemiş:'Badem, fındık, ceviz ve diğerleri','Yer fıstığı':'Yer fıstığı ve ürünleri',Soya:'Soya fasulyesi ve ürünleri',Balık:'Balık ve balık ürünleri',Kabuklular:'Karides, yengeç, ıstakoz',Yumuşakçalar:'Midye, kalamar ve benzerleri',Susam:'Susam ve tahin',Hardal:'Hardal ve içeren soslar',Kereviz:'Kereviz ve kereviz ürünleri','Acı bakla':'Acı bakla ve ürünleri',Sülfitler:'Kükürt dioksit ve sülfitler'};

export const billingSchema=z.object({type:z.enum(['individual','company']),name:z.string().max(120),email:z.string().max(150),companyName:z.string().max(160),taxOffice:z.string().max(100),taxNumber:z.string().max(11),sameAsDelivery:z.boolean(),city:z.string().max(50),district:z.string().max(70),address:z.string().max(500)}).strict();
export type Billing=z.infer<typeof billingSchema>;
export const initialBilling:Billing={type:'individual',name:'',email:'',companyName:'',taxOffice:'',taxNumber:'',sameAsDelivery:true,city:'İstanbul',district:'',address:''};
type Delivery={name:string;phone:string;city:string;district:string;address:string};
export function deliveryError(p:Delivery){if(p.city!=='İstanbul'||!istanbulDistricts.includes(p.district as typeof istanbulDistricts[number]))return 'Teslimat için İstanbul ilçelerinden birini seç.';if(p.name.trim().length<3||p.phone.replace(/\D/g,'').length<10||p.address.trim().length<10)return 'İsim, telefon ve açık adresini tamamla.';return '';}
export function billingError(b:Billing,p:Delivery){if(!z.string().email().safeParse(b.email).success)return 'Fatura için geçerli bir e-posta adresi gir.';if(b.type==='individual'&&b.name.trim().length<3)return 'Faturada yer alacak ad ve soyadı gir.';if(b.type==='company'&&(b.companyName.trim().length<2||b.taxOffice.trim().length<2||!/^\d{10,11}$/.test(b.taxNumber)))return 'Firma unvanı, vergi dairesi ve 10 veya 11 haneli vergi / kimlik numarasını tamamla.';const address=b.sameAsDelivery?p:b;if(!address.city.trim()||!address.district.trim()||address.address.trim().length<10)return 'Fatura adresini tamamla.';return '';}
export function billingSnapshot(b:Billing,p:Delivery):Billing{return {...b,...(b.sameAsDelivery?{city:p.city,district:p.district,address:p.address}:{}),...(b.type==='individual'?{companyName:'',taxOffice:'',taxNumber:''}:{name:''})};}
export function allergyError(p:{allergenStatus:string;allergens:readonly string[];allergyNotes?:string}){if(p.allergenStatus==='unset')return 'Alerjin olup olmadığını belirt.';if(p.allergenStatus==='selected'&&!p.allergens.length&&!p.allergyNotes?.trim())return 'Alerjenlerini seç veya listede olmayanları not alanına yaz.';if(p.allergenStatus==='none'&&p.allergens.length)return 'Alerjen seçimlerini kontrol et.';return '';}

// A reviewable store assortment. These individual product prices are examples,
// not live inventory or a payment offer. The storefront labels them accordingly.
const recipeProduct=(recipeId:string,price:number,category:string)=>{const r=recipes.find(r=>r.id===recipeId)!;return {id:recipeId,name:r.name,description:r.description,image:r.image,price,category,unit:'1 porsiyon',allergens:r.allergens,ingredients:r.ingredients.map(i=>i.name),kcal:r.kcal,protein:r.protein,carbs:r.carbs,fat:r.fat};};
export const shopProducts=[recipeProduct('tavuk-bowl',390,'Bowllar'),recipeProduct('nohut-bowl',340,'Bowllar'),recipeProduct('tavuk-wrap',320,'Wrapler'),recipeProduct('granola',180,'Kahvaltı'),recipeProduct('meyveli-yogurt',120,'Ara öğünler'),{id:'yesil-icecek',name:'Yeşil meyve & sebze içeceği',description:'Elma, salatalık, ıspanak, limon ve zencefil.',image:'/images/zepe-hero-food.png',price:175,category:'İçecekler',unit:'250 ml',allergens:[] as string[],ingredients:['Elma','Salatalık','Ispanak','Limon','Zencefil'],kcal:null,protein:null,carbs:null,fat:null}];
export type ShopProduct=typeof shopProducts[number];
export const shopItemSchema=z.object({id:z.string().min(1).max(80),productId:z.enum(shopProducts.map(p=>p.id) as [string,...string[]]),quantity:z.number().int().min(1).max(20)}).strict();
export type ShopItem=z.infer<typeof shopItemSchema>;
export function shopTotal(items:ShopItem[]){return items.reduce((sum,item)=>{const product=shopProducts.find(p=>p.id===item.productId);if(!product)throw new Error('Ürün bulunamadı.');return sum+product.price*item.quantity;},0);}
