export const money=(n:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(n);
export const images={bowl:'/images/hero-bowl.webp',salmon:'https://images.pexels.com/photos/1516415/pexels-photo-1516415.jpeg?auto=compress&dpr=1&h=750&w=1260',oats:'https://images.unsplash.com/photo-1490371475955-4cb3bfc72f71?auto=format&fit=crop&w=900&q=85',wrap:'https://images.pexels.com/photos/29535640/pexels-photo-29535640/free-photo-of-fresh-chicken-wrap-with-avocado-and-veggies.jpeg?auto=compress&dpr=1&h=750&w=1260',vegan:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85'};
export const packages=[
{id:'dengeli-beslenme',name:'Dengeli Beslenme',original:'Zayıflama & Dengeli Beslenme',tag:'Dengeni bul',description:'Günün ritmine uyum sağlayan, sana özel porsiyonlarla dengeli ve çeşitli öğünler.',price:1050,image:images.vegan,goal:'balance',meals:3,features:['Kişiye özel porsiyon planı','3 ana öğün ve ara öğünler','Diyetisyen görüşmesi'],source:'https://www.zepeapp.com/product-page/zayiflama'},
{id:'yuksek-protein',name:'Yüksek Protein',original:'Sporcu & Yüksek Protein',tag:'Harekete güç kat',description:'Aktif günlerine eşlik eden, protein odaklı ve doyurucu bir beslenme düzeni.',price:1050,image:images.bowl,goal:'muscle',meals:3,features:['Protein odaklı öğünler','3 ana öğün ve ara öğünler','Hedefine göre porsiyonlama'],source:'https://www.zepeapp.com/product-page/sporcu-yuksek-protein'},
{id:'tek-ogun',name:'Tek Öğün',original:'Tek Öğün',tag:'Gününe iyi gelsin',description:'Yoğun günün ortasında kendine bir iyilik. Şeflerin hazırladığı tek, dengeli öğün.',price:450,image:images.salmon,goal:'practical',meals:1,features:['Öğle veya akşam seçeneği','Bir ana öğün ve ara öğün','Evine veya ofisine teslimat'],source:'https://www.zepeapp.com/product-page/tek-ogun'},
{id:'aralikli-oruc',name:'Aralıklı Oruç',original:'Aralıklı Oruç',tag:'Kendi ritminde',description:'Tercih ettiğin öğün saatlerine uyum sağlayan, diyetisyen eşliğinde planlanan menüler.',price:1000,image:images.wrap,goal:'balance',meals:2,features:['İki ana öğün seçeneği','Öğün saatlerini kişiselleştirme','Diyetisyen değerlendirmesi'],source:'https://www.zepeapp.com/product-page/aralikli-oruc'},
{id:'detoks',name:'Detoks',original:'Detoks',tag:'Meyve ve sebzeyle',description:'Meyve ve sebze içeceklerinden oluşan kısa süreli program. Uygunluğu diyetisyenle değerlendirilir.',price:1050,image:images.vegan,goal:'light',meals:6,features:['6 farklı içecek','Kısa süreli program','Başlamadan diyetisyen görüşmesi'],source:'https://www.zepeapp.com/product-page/detoks'},
{id:'kati-sivi-detoks',name:'Katı & Sıvı Detoks',original:'Katı & Sıvı Detoks',tag:'Bir arada',description:'Bir ana öğün ve meyve-sebze içeceklerinin bir araya geldiği kısa süreli seçenek.',price:1150,image:images.bowl,goal:'light',meals:5,features:['Protein içeren bir ana öğün','4 meyve-sebze içeceği','3 veya 5 günlük plan'],source:'https://www.zepeapp.com/product-page/kati-sivi-detoks'}
];
export type Package=typeof packages[number];
export type Ingredient={name:string;amount:number;unit:string;group:string};
export type Recipe={id:string;name:string;description:string;category:string;image:string;kcal:number;protein:number;carbs:number;fat:number;minutes:number;diet:'vegan'|'vegetarian'|'fish'|'meat';allergens:string[];ingredients:Ingredient[];steps:string[]};
const ing=(name:string,amount:number,group='Sebze & meyve',unit='g'):Ingredient=>({name,amount,unit,group});
export const recipes:Recipe[]=[
{id:'tavuk-bowl',name:'Izgara tavuk & kinoa bowl',description:'Avokado, kinoa, edamame ve bol yeşillik.',category:'Öğle',image:images.bowl,kcal:548,protein:42,carbs:50,fat:20,minutes:25,diet:'meat',allergens:['Soya'],ingredients:[ing('Tavuk göğsü',140,'Protein'),ing('Kinoa',50,'Tahıl & bakliyat'),ing('Avokado',40),ing('Edamame',30,'Tahıl & bakliyat'),ing('Çeri domates',60),ing('Yeşillik',40),ing('Zeytinyağı',5,'Diğer')],steps:['Kinoayı yıkayıp paketteki pişirme talimatına göre haşla.','Tavuğu iyice pişene kadar ızgarada pişir. Dilimle.','Sebzeleri yıka ve doğra. Tüm malzemeleri kasede birleştir; zeytinyağı ve limonla tamamla.']},
{id:'somon',name:'Fırın somon & mevsim sebzeleri',description:'Fırın somon, renkli sebzeler ve taze otlar.',category:'Akşam',image:images.salmon,kcal:536,protein:38,carbs:33,fat:28,minutes:30,diet:'fish',allergens:['Balık'],ingredients:[ing('Somon',160,'Protein'),ing('Patates',140),ing('Kabak',100),ing('Havuç',60),ing('Zeytinyağı',8,'Diğer')],steps:['Fırını 200 dereceye getir. Sebzeleri eşit boyda doğra.','Sebzeleri zeytinyağıyla harmanlayıp fırına ver.','Somonu ekle; balık ve sebzeler tamamen pişene kadar pişir. Limon ve taze otlarla servis et.']},
{id:'granola',name:'Orman meyveli yoğurt & granola',description:'Yoğurt, yulaf ve orman meyveleri.',category:'Kahvaltı',image:images.oats,kcal:356,protein:20,carbs:51,fat:8,minutes:5,diet:'vegetarian',allergens:['Süt','Gluten'],ingredients:[ing('Yoğurt',180,'Süt ürünleri'),ing('Yulaf',40,'Tahıl & bakliyat'),ing('Orman meyveleri',80),ing('Chia tohumu',8,'Diğer')],steps:['Yoğurdu bir kaseye al.','Yulafı, yıkanmış orman meyvelerini ve chia tohumunu ekle.','Karıştır veya katmanlar halinde servis et.']},
{id:'tavuk-wrap',name:'Avokadolu tavuk wrap',description:'Izgara tavuk, avokado ve çıtır yeşillikler.',category:'Öğle',image:images.wrap,kcal:496,protein:36,carbs:43,fat:20,minutes:20,diet:'meat',allergens:['Gluten'],ingredients:[ing('Tavuk göğsü',120,'Protein'),ing('Tam buğday lavaş',60,'Tahıl & bakliyat'),ing('Avokado',50),ing('Domates',60),ing('Yeşillik',40),ing('Zeytinyağı',5,'Diğer')],steps:['Tavuğu iyice pişene kadar ızgarada pişir.','Lavaşı hafifçe ısıt. Avokadoyu ezerek üzerine sür.','Dilimlenmiş tavuk, domates ve yeşillikleri ekleyip sıkıca sar.']},
{id:'nohut-bowl',name:'Renkli nohut & sebze bowl',description:'Nohut, tatlı patates, avokado ve taze sebzeler.',category:'Öğle',image:images.vegan,kcal:484,protein:17,carbs:68,fat:16,minutes:25,diet:'vegan',allergens:[],ingredients:[ing('Haşlanmış nohut',140,'Tahıl & bakliyat'),ing('Tatlı patates',100),ing('Avokado',40),ing('Çeri domates',70),ing('Yeşillik',40),ing('Zeytinyağı',5,'Diğer')],steps:['Tatlı patatesi küp doğrayıp zeytinyağıyla fırında yumuşayana kadar pişir.','Nohudu süz. Sebzeleri yıka ve doğra.','Tüm malzemeleri bir kasede birleştir. Limonla servis et.']},
{id:'mercimek-salata',name:'Yeşil mercimek salatası',description:'Mercimek, bol yeşillik ve limonlu zeytinyağı.',category:'Akşam',image:images.vegan,kcal:432,protein:20,carbs:61,fat:12,minutes:20,diet:'vegan',allergens:[],ingredients:[ing('Haşlanmış yeşil mercimek',200,'Tahıl & bakliyat'),ing('Domates',100),ing('Salatalık',100),ing('Yeşillik',60),ing('Zeytinyağı',10,'Diğer')],steps:['Haşlanmış mercimeği süz ve soğumaya bırak.','Sebzeleri ve yeşillikleri yıkayıp ince doğra.','Mercimekle birleştir. Zeytinyağı, limon ve dilediğin baharatlarla karıştır.']},
{id:'chia',name:'Meyveli chia puding',description:'Hindistan cevizi içeceği, chia ve taze meyve.',category:'Kahvaltı',image:images.oats,kcal:352,protein:8,carbs:35,fat:20,minutes:10,diet:'vegan',allergens:[],ingredients:[ing('Hindistan cevizi içeceği',200,'Diğer','ml'),ing('Chia tohumu',35,'Diğer'),ing('Muz',100),ing('Orman meyveleri',60)],steps:['Chia tohumunu hindistan cevizi içeceğiyle karıştır.','Buzdolabında en az 2 saat, tercihen gece boyunca beklet.','Dilimlenmiş muz ve yıkanmış meyvelerle tamamla.']},
{id:'meyveli-yogurt',name:'Meyveli yoğurt',description:'Günün küçük molası: yoğurt ve orman meyveleri.',category:'Ara öğün',image:images.oats,kcal:164,protein:10,carbs:22,fat:4,minutes:3,diet:'vegetarian',allergens:['Süt'],ingredients:[ing('Yoğurt',150,'Süt ürünleri'),ing('Orman meyveleri',80)],steps:['Meyveleri yıka.','Yoğurda ekleyip karıştırarak servis et.']},
{id:'meyve-chia',name:'Meyveli chia kup',description:'Chia pudingin meyveli, küçük porsiyonu.',category:'Ara öğün',image:images.oats,kcal:208,protein:4,carbs:30,fat:8,minutes:5,diet:'vegan',allergens:[],ingredients:[ing('Chia tohumu',15,'Diğer'),ing('Hindistan cevizi içeceği',100,'Diğer','ml'),ing('Muz',80),ing('Orman meyveleri',50)],steps:['Chia ile hindistan cevizi içeceğini karıştırıp buzdolabında en az 2 saat beklet.','Meyveleri ekleyip servis et.']},
{id:'kinoa-akdeniz',name:'Akdeniz kinoa salatası',description:'Kinoa, domates, salatalık ve taze otlar.',category:'Akşam',image:images.vegan,kcal:456,protein:14,carbs:64,fat:16,minutes:20,diet:'vegan',allergens:[],ingredients:[ing('Kinoa',80,'Tahıl & bakliyat'),ing('Domates',100),ing('Salatalık',100),ing('Avokado',40),ing('Yeşillik',40),ing('Zeytinyağı',8,'Diğer')],steps:['Kinoayı yıkayıp paketteki talimata göre haşla.','Soğumuş kinoayı doğranmış sebze ve otlarla karıştır.','Avokado, zeytinyağı ve limonla tamamla.']}
];
export const articles=[
{id:'dengeli-tabak',type:'Rehber',category:'Dengeli beslenme',title:'İyi beslenmek, iyi bir tabakla başlar.',excerpt:'Günlük öğünlerinde çeşitliliğe yer açmanın pratik yolları.',minutes:3,body:[['Tabakta çeşitliliğe yer aç','Sebze ve meyveleri, tam tahılları ve farklı protein kaynaklarını gün içine yaymak, çeşitli bir beslenme düzeni kurmanın pratik yoludur. Tek bir besini kusursuz hale getirmek yerine haftanın bütününe bak.'],['Küçük bir başlangıç','Öğle yemeğine bir sebze ekle, bazı günler bakliyat seç ve suyu elinin altında tut. Alışkanlıklarını günlük hayatına uyacak şekilde düzenle.'],['Kendine göre planla','Porsiyon ve öğün düzeni herkes için aynı değildir. Tercihlerini, günlük hareketini ve özel ihtiyaçlarını diyetisyeninle birlikte değerlendir.']],source:'https://www.who.int/news-room/fact-sheets/detail/healthy-diet',sourceLabel:'Dünya Sağlık Örgütü — Healthy diet'},
{id:'protein',type:'Kısa okuma',category:'Protein',title:'Protein sadece spor günleri için değil.',excerpt:'Protein kaynaklarını günlük düzenine nasıl dahil edebilirsin?',minutes:2,body:[['Farklı kaynakları tanı','Balık, tavuk, yumurta, süt ürünleri ve bakliyatlar protein sağlayan besinler arasındadır. Tercihlerine uygun kaynakları haftaya yaymak çeşitlilik sağlar.'],['Rakamlar kişiseldir','Protein ihtiyacı yaşa, vücut ağırlığına, aktiviteye ve sağlık durumuna göre değişir. Bir başkasının gram hedefi senin için doğru olmayabilir.'],['Öğünün bütününü düşün','Protein kaynağının yanında sebze, tam tahıl ve uygun yağ kaynaklarına da yer ver. Daha fazla protein tek başına daha dengeli bir beslenme anlamına gelmez.']],source:'https://www.nhs.uk/live-well/eat-well/how-to-eat-a-balanced-diet/eating-a-balanced-diet/',sourceLabel:'NHS — Eating a balanced diet'},
{id:'su',type:'Kısa okuma',category:'Günlük alışkanlıklar',title:'Bir bardak suyla başlayan alışkanlık.',excerpt:'Su içmeyi gününün doğal bir parçasına dönüştür.',minutes:2,body:[['Herkes için tek bir sayı yok','Sıvı ihtiyacı hareket, hava sıcaklığı ve kişisel koşullara göre değişir. İçecekler ve yiyecekler de günlük sıvı alımına katkıda bulunur.'],['Görünür kıl','Masanın üstünde bir bardak su bulundurmak ya da öğünlerin yanında su içmek, hatırlamayı kolaylaştırır. Sıcak havalarda ve egzersiz sırasında ihtiyacının artabileceğini unutma.'],['Küçük ve sürdürülebilir','Gün içinde düzenli olarak içmek iyi bir başlangıçtır. Sağlık nedeniyle sıvı kısıtlaman varsa kendi sağlık ekibinin önerisini takip et.']],source:'https://www.nhs.uk/live-well/eat-well/food-guidelines-and-food-labels/water-drinks-nutrition/',sourceLabel:'NHS — Water, drinks and hydration'},
{id:'kalori-tahmini',type:'Kaynak',category:'Enerji dengesi',title:'Kalori hesabı neyi söyler, neyi söylemez?',excerpt:'Günlük enerji tahmininin ardındaki yöntemi tanı.',minutes:3,body:[['Bir başlangıç tahmini','Mifflin–St Jeor denklemi yaş, boy, ağırlık ve cinsiyet bilgileriyle dinlenme enerji harcamasını tahmin eder. Günlük hareket için kullanılan katsayıyla toplam enerji harcamasına yaklaşılır.'],['Ölçüm değildir','Bir formül, bireysel metabolizmanı doğrudan ölçmez. Sonuç yaklaşık bir başlangıç değeridir; sağlık durumu, beden kompozisyonu ve gerçek hareket düzeyi farklılık yaratabilir.'],['Zepe planında nasıl kullanılır?','Planlayıcı bir enerji referansı gösterir ve örnek tarif porsiyonlarını bu değere göre ölçekler. Kilo verme veya tedavi amaçlı kesin hedef belirlemez. Kişisel beslenme hedefini diyetisyeninle netleştir.']],source:'https://pubmed.ncbi.nlm.nih.gov/2305711/',sourceLabel:'Mifflin ve arkadaşları, 1990 — American Journal of Clinical Nutrition'}
];
export const faqs=[['Zepe nasıl çalışır?','Paketini seçersin; diyetisyen görüşmesinde ihtiyaçların ve porsiyonların değerlendirilir. Öğünlerin taze hazırlanır, teslimat planına göre evine veya ofisine ulaştırılır.'],['Menüyü kişiselleştirebilir miyim?','Besin tercihlerini ve sevmediğin malzemeleri planlayıcıya ekleyebilirsin. Yemek aboneliğinde uygulanacak değişiklikler ve alerjen uygunluğu Zepe ekibiyle kesinleştirilir.'],['Hangi bölgelere teslimat var?','Teslimat uygunluğu İstanbul içinde adres bazında kontrol edilir. Adresini Zepe ekibiyle paylaşarak güncel bölge ve teslimat saatini öğrenebilirsin.'],['Teslimatı erteleyebilir miyim?','Teslimat günü değişiklikleri ve ara verme koşulları mevcut aboneliğine göre Zepe ekibiyle netleştirilir. Bu sitedeki dijital planını ise istediğin zaman değiştirebilirsin.'],['Burada ödeme yapabilir miyim?','Bu sürümde paketini seçip sipariş taslağını kaydedebilirsin. Ödeme ve teslimat onayı Zepe ekibiyle veya mevcut zepeapp.com sipariş kanalı üzerinden tamamlanır.'],['Besin değerleri kesin mi?','Tariflerdeki değerler örnek porsiyonlara ait yaklaşık değerlerdir. Teslim edilecek öğünlerin içeriği ve kişisel porsiyonların diyetisyen görüşmesinde netleşir.']];
