import {z} from 'zod';
import {recipes,packages} from './data';
import {quote,selectionsValid} from './pricing';
import {allergens,billingSchema,initialBilling,shopItemSchema,type Billing,type ShopItem,type Allergen} from './commerce';
export const profileSchema=z.object({name:z.string().max(100),phone:z.string().max(30),address:z.string().max(500),city:z.literal('İstanbul'),district:z.string().max(70),goal:z.enum(['balance','muscle','practical']),diet:z.enum(['all','vegetarian','vegan','pescatarian']),sex:z.enum(['male','female']),age:z.number().min(18).max(100),height:z.number().min(120).max(230),weight:z.number().min(35).max(250),activity:z.enum(['low','light','active','very']),meals:z.number().int().min(3).max(5),allergens:z.array(z.enum(allergens)).max(14),allergenStatus:z.enum(['unset','none','selected']).default('unset'),allergyNotes:z.string().max(500).default(''),exclusions:z.string().max(300)}).strict();
export type Profile=z.infer<typeof profileSchema>;
export const cartItemSchema=z.object({id:z.string().max(80),packageId:z.enum(packages.map(p=>p.id) as [string,...string[]]),days:z.union([z.literal(1),z.literal(3),z.literal(5),z.literal(15),z.literal(30)]),people:z.number().int().min(1).max(10),startDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),mealOption:z.string().max(70),notes:z.string().max(500),selectedMeals:z.array(z.enum(['breakfast','lunch','dinner'])).max(3).optional(),snacks:z.number().int().min(0).max(2).optional()}).strict().refine(selectionsValid,'Paket ve öğün seçimi birbiriyle uyumlu olmalı.').refine(v=>v.packageId!=='kati-sivi-detoks'||[3,5].includes(v.days),'Bu paket 3 veya 5 gün olabilir.').refine(v=>v.packageId!=='detoks'||[1,3,5].includes(v.days),'Detoks 1, 3 veya 5 gün olabilir.');
export type CartItem=z.infer<typeof cartItemSchema>;
export const mealSchema=z.object({recipeId:z.enum(recipes.map(r=>r.id) as [string,...string[]]),servings:z.number().min(.25).max(5),slot:z.string().max(30)}).strict();
export type PlanMeal=z.infer<typeof mealSchema>;
export const planSchema=z.object({start:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),days:z.array(z.array(mealSchema).min(1).max(5)).length(7),paused:z.boolean()}).strict();
export type MealPlan=z.infer<typeof planSchema>;
export type Draft={id:string;created:string;items:CartItem[];total:number;name:string;phone:string;address:string;city:string;district:string;status:'draft';shopItems?:ShopItem[];shopDeliveryDate?:string;billing?:Billing;allergens?:Allergen[];allergyNotes?:string;exclusions?:string};
export type State={profile:Profile;favorites:string[];cart:CartItem[];shopCart:ShopItem[];billing:Billing;shopDeliveryDate:string;plan:MealPlan|null;checked:string[];orders:Draft[];progress:{date:string;weight:number}[]};
export const initialProfile:Profile={name:'',phone:'',address:'',city:'İstanbul',district:'',goal:'balance',diet:'all',sex:'female',age:30,height:165,weight:65,activity:'light',meals:4,allergens:[],allergenStatus:'unset',allergyNotes:'',exclusions:''};
export const initialState:State={profile:initialProfile,favorites:[],cart:[],shopCart:[],billing:initialBilling,shopDeliveryDate:'',plan:null,checked:[],orders:[],progress:[]};
export const patchSchema=z.object({profile:profileSchema.optional(),favorites:z.array(z.string().max(90)).max(200).optional(),cart:z.array(cartItemSchema).max(20).optional(),shopCart:z.array(shopItemSchema).max(30).optional(),billing:billingSchema.optional(),shopDeliveryDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),plan:planSchema.nullable().optional(),checked:z.array(z.string().max(100)).max(300).optional(),progress:z.array(z.object({date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),weight:z.number().min(35).max(250)}).strict()).max(100).optional()}).strict();
export function localDate(d=new Date()){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
export function nextDate(days=1){const d=new Date(localDate()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
export function energy(p:Profile){return Math.round((10*p.weight+6.25*p.height-5*p.age+(p.sex==='male'?5:-161))*({low:1.2,light:1.375,active:1.55,very:1.725}[p.activity]));}
export function eligible(p:Profile){const excluded=p.exclusions.toLocaleLowerCase('tr-TR').split(',').map(x=>x.trim()).filter(Boolean);return recipes.filter(r=>(p.diet==='all'||p.diet==='vegan'&&r.diet==='vegan'||p.diet==='vegetarian'&&['vegetarian','vegan'].includes(r.diet)||p.diet==='pescatarian'&&r.diet!=='meat')&&!r.allergens.some(a=>p.allergens.includes(a as Profile['allergens'][number]))&&!r.ingredients.some(i=>excluded.some(e=>i.name.toLocaleLowerCase('tr-TR').includes(e))));}
export function createPlan(p:Profile,offset=0):MealPlan{const pool=eligible(p);const slots=p.meals===3?['Kahvaltı','Öğle','Akşam']:p.meals===5?['Kahvaltı','Ara öğün','Öğle','Ara öğün','Akşam']:['Kahvaltı','Öğle','Ara öğün','Akşam'];const days=Array.from({length:7},(_,d)=>{const selected=slots.map((slot,i)=>{let candidates=pool.filter(r=>r.category===slot);if(!candidates.length)throw new Error(`${slot} için tercihlerine uygun tarif bulunamadı. Hariç tuttuğun besinleri gözden geçirebilirsin.`);if(p.goal==='muscle'&&['Öğle','Akşam'].includes(slot)) candidates=candidates.sort((a,b)=>b.protein/b.kcal-a.protein/a.kcal);return{r:candidates[(d+i+offset)%candidates.length],slot}});const total=selected.reduce((s,x)=>s+x.r.kcal,0);const scale=Math.min(3,Math.max(.5,energy(p)/total));return selected.map(x=>({recipeId:x.r.id,servings:Math.round(scale*100)/100,slot:x.slot}));});return {start:localDate(),days,paused:false};}
export function totals(meals:PlanMeal[]){return meals.reduce((a,m)=>{const r=recipes.find(r=>r.id===m.recipeId)!;return{kcal:a.kcal+r.kcal*m.servings,protein:a.protein+r.protein*m.servings,carbs:a.carbs+r.carbs*m.servings,fat:a.fat+r.fat*m.servings}},{kcal:0,protein:0,carbs:0,fat:0})}
export function shopping(plan:MealPlan,family=1){const map=new Map<string,{name:string;amount:number;unit:string;group:string}>();for(const day of plan.days)for(const m of day){const r=recipes.find(r=>r.id===m.recipeId)!;for(const i of r.ingredients){const k=i.name+'|'+i.unit;const old=map.get(k);map.set(k,{...i,amount:(old?.amount||0)+i.amount*m.servings*family});}}return Array.from(map.values()).sort((a,b)=>a.group.localeCompare(b.group,'tr'))}
export function cartTotal(items:CartItem[]){return items.reduce((s,i)=>s+quote(i).total,0)}
